### ISSUE TITLE
Data Fetching hook?

### ISSUE THREAD

**Issue by mattfwood** [beizhedenglong/react-hooks-lib#2]
Has anyone had any luck creating a data fetching hook using useEffect?

I’ve tried a few things but I’m having issues with updating and changing data once it’s fetched. 

useEffect seems to work fine with any asynchronous functions, but I feel like I’m missing a piece

**Comment by beizhedenglong** [comment]
I have this plan.

**Comment by beizhedenglong** [comment]
#4
